version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8081:8000"
    environment:
      - AZURE_API_KEY=key # Make sure to pass your API key
      - AZURE_API_BASE=url
      - AZURE_API_VERSION=version 
      - MODELS=model
    volumes:
      - .:/app
    restart: unless-stopped
